services:
  mqtt:
    image: toke/mosquitto
    container_name: mqtt
    expose:
      - "1883"
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  casandra1:
    image: cassandra:latest
    container_name: casandra1
    expose:
      - "9042"
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    networks:
      - app-network
    volumes:
      - ./cassandra1:/var/lib/cassandra
   


  casandra2:
    image: cassandra:latest
    container_name: casandra2
    expose:
      - "9042"
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    networks:
      - app-network
    volumes:
      - ./cassandra2:/var/lib/cassandra
   


  fastapi1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controller1
    expose:
      - "8000"
    ports:
      - "8001:8000"  # Porta mapeada externamente para fastapi1
    restart: unless-stopped
    depends_on:
      - mqtt
      - casandra1
      - casandra2
    networks:
      - app-network
    environment:
      - INSTANCE=1
      - DB_CLUSTERS=casandra1
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"

  fastapi2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controller2
    expose:
      - "8000"
    ports:
      - "8002:8000"  # Porta mapeada externamente para fastapi2
    restart: unless-stopped
    depends_on:
      - mqtt
      - casandra1
      - casandra2
    networks:
      - app-network
    environment:
      - INSTANCE=2
      - DB_CLUSTERS=casandra2
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi1
      - fastapi2
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

networks:
  app-network:
    driver: bridge

volumes:
  cassandra1:
  cassandra2:
